Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,10 +38,10 @@ jobs:
       run: npm run test -- --watch=false --browsers=ChromeHeadless
 
     - name: Build Angular app
-      run: npm run build -- --base-href=/Ionut-Gardu/ --configuration=production
+      run: npx ng build --configuration=production --base-href=/Ionut-gardu/ --output-path=dist/browser
 
     - name: Copy 404.html for SPA routing
-      run: cp ./dist/tt-project/404.html ./dist/tt-project/404.html || echo "404.html not found, continuing..."
+      run: cp ./dist/browser/404.html ./dist/browser/404.html || echo "404.html not found, continuing..."
 
     - name: Setup Pages
       uses: actions/configure-pages@v4
@@ -49,7 +49,7 @@ jobs:
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v3
       with:
-        path: './dist/tt-project'
+        path: './dist/browser'
 
   deploy:
     environment:
